// Public, test-only loopback TLS identity; not a production credential.
exports.key = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgSwFv8zsSdFl1sT4q
cDd22UXL9g6vvbzGOMYdPzvrHMehRANCAATCT0vHym6MJIPIaF7MPTtOxcpt3WXR
bl4+yaDN1KbZjG10AqwJ1BJQq5kJBqd+WsoSiq4GpJH0u0lt8awivD9f
-----END PRIVATE KEY-----`;
exports.cert = `-----BEGIN CERTIFICATE-----
MIIBkzCCATmgAwIBAgIUGGFOPGznZNVgY7oWIKxjmfHL0N8wCgYIKoZIzj0EAwIw
FDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI2MTAwNjEyNTkwNloXDTM2MTAwMzEy
NTkwNlowFDESMBAGA1UEAwwJbG9jYWxob3N0MFkwEwYHKoZIzj0CAQYIKoZIzj0D
AQcDQgAEwk9Lx8pujCSDyGhezD07TsXKbd1l0W5ePsmgzdSm2YxtdAKsCdQSUKuZ
CQanflrKEoquBqSR9LtJbfGsIrw/X6NpMGcwHQYDVR0OBBYEFJ28awAZlHJdqqmN
EXFYa7hnmLDtMB8GA1UdIwQYMBaAFJ28awAZlHJdqqmNEXFYa7hnmLDtMA8GA1Ud
EwEB/wQFMAMBAf8wFAYDVR0RBA0wC4IJbG9jYWxob3N0MAoGCCqGSM49BAMCA0gA
MEUCIH3Jw4vYyAyITG3088IuHM4ix+MA+hKv3WfLEyN2rw+cAiEAgBJndYLUm1lM
lo4vLLjqNq6eMuJv00mU8s7L1Fmn5iM=
-----END CERTIFICATE-----`;
