import type { LimitsCopy } from "./limits-copy";

export const fr: LimitsCopy = {
  title: "Limites",
  subtitle: "Limites publiques de ChatGPT et messages observés par ce lanceur.",
  notConfigured: "Non configuré",
  setupTitle: "Suivre les messages envoyés ici",
  setupBody: "Configurez le suivi pour détecter votre offre ChatGPT dans le navigateur du lanceur. Disponible pour Pro 5x (100 $) et Pro 20x (200 $).",
  setup: "Configurer le suivi",
  checking: "Vérification de votre offre…",
  recheck: "Vérifier à nouveau l’offre",
  browserBusy: "Attendez la fin de la tâche ou de l’opération en cours dans le navigateur avant de vérifier votre offre.",
  loading: "Chargement du suivi enregistré…",
  refresh: "Actualiser",
  loadError: "Impossible de charger le suivi.",
  staleError: "Impossible d’actualiser le suivi. Les dernières données chargées sont affichées ci-dessous.",
  actionError: "Impossible de terminer cette action.",
  sourceError: "Impossible d’ouvrir la référence OpenAI.",
  zeroRisk: "Indisponible avec Zero Risk",
  zeroRiskBody: "La détection de l’offre et le suivi de l’utilisation sont indisponibles en mode Zero Risk. Les limites publiques de référence restent accessibles.",
  proOnly: "Suivi disponible uniquement pour les offres Pro",
  unsupportedBody: "Ce compte n’a pas été identifié comme Pro 5x (100 $) ou Pro 20x (200 $). Le suivi de Plus et des autres offres n’est pas disponible ici ; leurs limites chiffrées sont inconnues.",
  paused: "Suivi inactif",
  active: "Suivi du lanceur activé",
  estimate: "Estimation",
  observedTitle: "Utilisation observée",
  observedBody: "Messages enregistrés dans des périodes glissantes locales et comparés aux références publiées.",
  scopeTitle: "Seule l’activité via ce lanceur est comptée",
  scopeBody: "L’utilisation en dehors de ce lanceur est exclue. Ces estimations ne représentent pas le quota restant de votre compte. Les périodes glissantes de 24 heures et 7 jours ne déterminent pas l’heure de réinitialisation de ChatGPT.",
  noWindows: "Aucune période d’utilisation disponible pour le moment.",
  rollingDay: "24 heures glissantes",
  rollingWeek: "7 jours glissants",
  rollingHours: "{hours} heures glissantes",
  observed: "observés",
  nearLimit: "L’utilisation observée a atteint au moins 75 % d’une limite de référence",
  referenceCap: "Référence : {count} messages",
  uncertain: "Messages Pro non attribués sur cette période : {count}",
  sharedUnknown: "Inclut {count} messages avec un modèle Pro inconnu",
  lowerBound: "Au moins {count}",
  modelTotalUnknown: "Total du modèle inconnu",
  attributionBody: "Le modèle de certains messages Pro est inconnu. Les comptes par modèle sont des minimums ; les totaux partagés incluent ces messages.",
  combined: "Les deux modèles Pro",
  history: "Historique enregistré",
  historyBody: "Les messages des 7 derniers jours sont enregistrés sur cet appareil et conservés au redémarrage du lanceur. L’enregistrement commence à l’activation du suivi ; l’activité antérieure est exclue.",
  totalMessages: "Messages · 7 derniers jours",
  unknownPro: "Modèle Pro non identifié",
  unknownProBody: "Ces messages ne peuvent pas être attribués à un modèle Pro précis.",
  since: "Suivi depuis",
  checked: "Offre vérifiée",
  unknown: "Inconnu",
  referenceTitle: "Limites publiques de référence",
  referenceBody: "Quotas de chat pour GPT-6 Pro et GPT-5.6 Sol Pro. Ce sont des références, pas des mesures de votre compte. Les quotas Work et Codex sont distincts.",
  asOf: "Au {date}",
  source: "Référence OpenAI",
  referenceOnly: "À titre indicatif",
  shared: "Partagé entre les deux modèles Pro",
  day: "{count} / jour",
  week: "{count} / semaine",
  month: "{count} / mois",
  otherPlans: "Plus et autres offres",
  otherPlansBody: "Quotas chiffrés inconnus. Le suivi du lanceur est disponible uniquement pour Pro 5x (100 $) et Pro 20x (200 $).",
  businessBody: "Les quotas Business sont présentés à titre indicatif. Le suivi Business n’est pas pris en charge.",
};
