export const zeroRiskCopy = {
  en: {
    manualPromptWaiting: "Sent. Waiting for the connector to start; do not resend.",
    manualPromptSeconds: "seconds remaining",
    manualMcpStepThreeBody: "Create the connector using the exact name below, then select it yourself in ChatGPT for every turn before sending the copied prompt.",
    manualConnectorNotice: "Use a separate Zero Risk tunnel and credentials; do not reuse Automatic credentials. Verify checks only the local runtime, not the ChatGPT connector or your selection. Keep the normal and DEV profiles separate.",
    manualBiggerContextBody: "Unavailable in Zero Risk. Manual turns use the selected route's standard compaction threshold, without multipart staging.",
    interactionMode: "Zero Risk",
    interactionModeOnboardingBody: "Choose how the launcher works with ChatGPT. Automation is the default and can be changed later in Settings.",
    automaticInteraction: "With Automation",
    automaticInteractionBody: "Automatically sends prompts and reads ChatGPT page state. Browser automation may conflict with ChatGPT terms or account policies.",
    manualInteraction: "Zero Risk",
    manualInteractionBody: "Never reads or changes ChatGPT. You paste and send each prompt yourself.",
    zeroRiskModelSettings: "Zero Risk model profiles",
    zeroRiskModelSettingsBody: "Expose the optional Pro route. Requires a ChatGPT Pro account and selecting Pro yourself in ChatGPT every turn. The larger limit may not work with every effort; Zero Risk cannot verify your subscription or selection.",
    manualPromptTitle: "Send this turn in ChatGPT",
    manualPromptInstruction: "Paste the copied prompt, choose the Codex Zero Risk connector, model, and effort, send it, then confirm below.",
    manualPromptCopy: "Copy prompt",
    manualPromptSent: "Sent",
  },
  "zh-CN": {
    manualPromptWaiting: "已送出，正在等待連接器啟動，請勿重複送出。",
    manualPromptSeconds: "秒剩餘",
    manualMcpStepThreeBody: "依下方顯示的完整名稱建立連接器；每一回合都需自行在 ChatGPT 選取它，再送出已複製的提示。",
    manualConnectorNotice: "請使用獨立的 Zero Risk Tunnel 與憑據，不可重用 Automatic 憑據。「驗證」只檢查本機 runtime，不檢查 ChatGPT 連接器或你的選取狀態。一般與 DEV 設定也需保持分離。",
    manualBiggerContextBody: "Zero Risk 不支援 Bigger Context；手動回合使用所選路由的標準壓縮門檻，不使用分段傳送。",
    interactionMode: "Zero Risk",
    interactionModeOnboardingBody: "選擇啟動器與 ChatGPT 的互動方式。預設使用自動化，之後可在設定中變更。",
    automaticInteraction: "自動化模式",
    automaticInteractionBody: "自動傳送提示並讀取 ChatGPT 頁面狀態。瀏覽器自動化可能與 ChatGPT 條款或帳戶政策衝突。",
    manualInteraction: "零風險",
    manualInteractionBody: "完全不讀取或修改 ChatGPT；每次提示都由你自行貼上與送出。",
    zeroRiskModelSettings: "Zero Risk 模型設定",
    zeroRiskModelSettingsBody: "額外提供 Pro 路由。需要 ChatGPT Pro 帳戶，且每回合都需自行在 ChatGPT 選擇 Pro。較大的額度不保證適用每種 effort；Zero Risk 無法驗證你的訂閱或選取狀態。",
    manualPromptTitle: "在 ChatGPT 中送出此回合",
    manualPromptInstruction: "貼上已複製的提示，選擇 Codex Zero Risk 連接器、模型與 effort，送出後在下方確認。",
    manualPromptCopy: "複製提示",
    manualPromptSent: "已送出",
  },
  ja: {
    manualPromptWaiting: "送信済み。コネクタの開始を待っています。再送信しないでください。",
    manualPromptSeconds: "秒残り",
    manualMcpStepThreeBody: "下に表示された正確な名前でコネクタを作成してください。各ターンで ChatGPT 上のコネクタを自分で選び、コピーしたプロンプトを送信します。",
    manualConnectorNotice: "Zero Risk 専用のトンネルと認証情報を使い、Automatic の認証情報を再利用しないでください。「検証」はローカル runtime のみを確認し、ChatGPT のコネクタや選択状態は確認しません。通常と DEV のプロファイルも分離してください。",
    manualBiggerContextBody: "Zero Risk では使用できません。手動ターンは選択したルートの標準圧縮しきい値を使い、分割送信しません。",
    interactionMode: "Zero Risk",
    interactionModeOnboardingBody: "ランチャーが ChatGPT を操作する方法を選びます。既定は自動操作で、後から設定で変更できます。",
    automaticInteraction: "自動操作あり",
    automaticInteractionBody: "プロンプトを自動送信し、ChatGPT のページ状態を読み取ります。ブラウザー自動操作は ChatGPT の規約やアカウントポリシーに抵触する可能性があります。",
    manualInteraction: "ゼロリスク",
    manualInteractionBody: "ChatGPT を読み書きせず、プロンプトの貼り付けと送信を手動で行います。",
    zeroRiskModelSettings: "Zero Risk モデル設定",
    zeroRiskModelSettingsBody: "追加の Pro ルートを公開します。ChatGPT Pro アカウントが必要で、毎ターン ChatGPT で自分で Pro を選択してください。大きい上限はすべての effort で使えるとは限りません。Zero Risk は契約や選択状態を検証できません。",
    manualPromptTitle: "このターンを ChatGPT で送信",
    manualPromptInstruction: "コピー済みのプロンプトを貼り付け、Codex Zero Risk コネクタ、モデル、effort を選んで送信し、下で確認してください。",
    manualPromptCopy: "プロンプトをコピー",
    manualPromptSent: "送信済み",
  },
} as const;
