export const zeroRiskCopy = {
  en: {
    manualBiggerContextBody: "Unavailable in Zero Risk. Manual turns use the selected route's standard compaction threshold, without multipart staging.",
    interactionMode: "Zero Risk",
    interactionModeOnboardingBody: "Choose how the launcher works with ChatGPT. Automation is the default and can be changed later in Settings.",
    automaticInteraction: "With Automation",
    automaticInteractionBody: "Automatically sends prompts and reads ChatGPT page state.",
    manualInteraction: "Zero Risk",
    manualInteractionBody: "Never reads or changes ChatGPT. You paste and send each prompt yourself.",
    zeroRiskModelSettings: "Zero Risk model profiles",
    zeroRiskModelSettingsBody: "Also expose the optional Pro route while Zero Risk is active.",
    manualPromptTitle: "Send this turn in ChatGPT",
    manualPromptInstruction: "Paste the copied prompt, choose the Codex Zero Risk connector, model, and effort, send it, then confirm below.",
    manualPromptCopy: "Copy prompt",
    manualPromptSent: "Sent",
  },
  "zh-CN": {
    manualBiggerContextBody: "Zero Risk 不支援 Bigger Context；手動回合使用所選路由的標準壓縮門檻，不使用分段傳送。",
    interactionMode: "Zero Risk",
    interactionModeOnboardingBody: "選擇啟動器與 ChatGPT 的互動方式。預設使用自動化，之後可在設定中變更。",
    automaticInteraction: "自動化模式",
    automaticInteractionBody: "自動傳送提示並讀取 ChatGPT 頁面狀態。",
    manualInteraction: "零風險",
    manualInteractionBody: "完全不讀取或修改 ChatGPT；每次提示都由你自行貼上與送出。",
    zeroRiskModelSettings: "Zero Risk 模型設定",
    zeroRiskModelSettingsBody: "在 Zero Risk 啟用時額外提供選用的 Pro 路由。",
    manualPromptTitle: "在 ChatGPT 中送出此回合",
    manualPromptInstruction: "貼上已複製的提示，選擇 Codex Zero Risk 連接器、模型與 effort，送出後在下方確認。",
    manualPromptCopy: "複製提示",
    manualPromptSent: "已送出",
  },
  ja: {
    manualBiggerContextBody: "Zero Risk では使用できません。手動ターンは選択したルートの標準圧縮しきい値を使い、分割送信しません。",
    interactionMode: "Zero Risk",
    interactionModeOnboardingBody: "ランチャーが ChatGPT を操作する方法を選びます。既定は自動操作で、後から設定で変更できます。",
    automaticInteraction: "自動操作あり",
    automaticInteractionBody: "プロンプトを自動送信し、ChatGPT のページ状態を読み取ります。",
    manualInteraction: "ゼロリスク",
    manualInteractionBody: "ChatGPT を読み書きせず、プロンプトの貼り付けと送信を手動で行います。",
    zeroRiskModelSettings: "Zero Risk モデル設定",
    zeroRiskModelSettingsBody: "Zero Risk の使用中に任意の Pro ルートも公開します。",
    manualPromptTitle: "このターンを ChatGPT で送信",
    manualPromptInstruction: "コピー済みのプロンプトを貼り付け、Codex Zero Risk コネクタ、モデル、effort を選んで送信し、下で確認してください。",
    manualPromptCopy: "プロンプトをコピー",
    manualPromptSent: "送信済み",
  },
} as const;
